import { Category } from "../types";

export const categoryKeywords = {
  health: [
    "hospital",
    "doctor",
    "medical",
    "treatment",
    "medicine",
    "healthcare",
    "clinic",
    "prescription",
    "diagnosis",
    "appointment",
    "emergency",
    "insurance",
    "pharmacy",
    "symptoms",
    "vaccination",
    "dental",
    "surgery",
    "physician",
    "specialist",
    "therapy",
    "rehabilitation",
    "injection",
    "ICU",
    "OPD",
    "medication",
    "scan",
    "X-ray",
    "MRI",
    "ultrasound",
    "malpractice",
    "misdiagnosis",
    "side effects",
    "waiting time",
    "rude staff",
    "poor care",
    "hygiene",
    "sanitation",
    "overcharge",
    "wrong medication",
    "negligence",
    "infection",
    "discharge",
    "referral",
    "follow-up",
    "ambulance",
    "emergency response",
    "lab report",
    "test results",
    "billing",
    "ward",
    "nurse",
    "paramedic",
    "blood test",
    "pathology",
    "negligent",
    "incompetent doctor",
    "wrong treatment",
    "botched",
    "painful",
    "suffering",
    "traumatic",
    "life-threatening",
    "fatal error",
    "medical horror",
    "dangerous",
    "unhealthy",
    "infected",
    "contaminated",
    "unsanitary conditions",
    "medical nightmare",
    "hospital hell",
    "cruel staff",
    "medical abuse",
    "neglected",
    "abandoned",
    "ignored",
    "medical disaster",
    "health hazard",
    "risky",
    "understaffed",
    "inexperienced",
    "medical mess",
    "health risk",
    "dangerous practice",
    "unqualified",
    "medical error",
    "fatal mistake",
    "critical failure",
    "emergency fail",
    "medical negligence",
    "hospital horror",
    "medical malpractice",
    "patient abuse",
    "medical scandal",
    "healthcare nightmare",
    "medical incompetence",
    "hospital disaster",
    "medical tragedy",
    "healthcare hell",
    "medical mishap",
    "hospital chaos",
    "medical blunder",
    "healthcare horror",
    "medical catastrophe",
    "health insurance claim",
    "medical report",
    "health checkup",
    "preventive care",
    "outpatient",
    "inpatient",
    "critical care",
    "emergency room",
    "urgent care",
    "primary care",
    "specialist consultation",
    "medical test",
    "lab work",
    "medical procedure",
    "medical equipment",
    "medical supplies",
    "patient care",
    "medical records",
    "medical history",
    "medical certificate",
    "health advisory",
    "defective",
    "vaccine"
  ],
  transport: [
    "bus",
    "train",
    "taxi",
    "flight",
    "ticket",
    "booking",
    "delay",
    "cancellation",
    "schedule",
    "route",
    "driver",
    "vehicle",
    "metro",
    "travel",
    "passenger",
    "fare",
    "reservation",
    "traffic",
    "car rental",
    "bike taxi",
    "ferry",
    "rideshare",
    "shuttle",
    "trip",
    "commute",
    "railway",
    "breakdown",
    "accident",
    "late",
    "rude driver",
    "overcharging",
    "unsafe",
    "dirty",
    "uncomfortable",
    "missed",
    "lost luggage",
    "poor service",
    "overcrowded",
    "technical fault",
    "broken ac",
    "bad condition",
    "strike",
    "detour",
    "road work",
    "conductor",
    "platform",
    "station",
    "terminal",
    "parking",
    "stranded",
    "abandoned",
    "nightmare journey",
    "horrible ride",
    "transport hell",
    "dangerous driver",
    "reckless driving",
    "scary ride",
    "nightmare trip",
    "transport disaster",
    "horrible experience",
    "worst service",
    "terrible journey",
    "transport horror",
    "travel nightmare",
    "awful commute",
    "transport mess",
    "chaotic journey",
    "travel disaster",
    "commute hell",
    "transport failure",
    "journey from hell",
    "travel horror",
    "transport chaos",
    "commute nightmare",
    "rip-off fare",
    "daylight robbery",
    "price gouging",
    "fare scam",
    "overcharged",
    "never arrived",
    "always late",
    "never on time",
    "unreliable service",
    "constant delays",
    "dangerous vehicle",
    "death trap",
    "unsafe transport",
    "risky ride",
    "accident waiting to happen",
    "terrible condition",
    "falling apart",
    "broken down",
    "mechanical issues",
    "safety hazard",
    "airline",
    "public transport",
    "transport service",
    "transportation",
    "transit",
    "mass transit",
    "ride booking",
    "cab service",
    "auto rickshaw",
    "transport app",
    "ride cancellation",
    "peak pricing",
    "surge pricing",
    "waiting charges",
    "toll charges",
    "night charges",
    "luggage charges",
    "route deviation",
    "traffic jam",
    "road closure",
    "vehicle maintenance",
  ],
  education: [
    "school",
    "college",
    "university",
    "course",
    "exam",
    "fee",
    "admission",
    "teacher",
    "student",
    "class",
    "lecture",
    "assignment",
    "grade",
    "certificate",
    "degree",
    "education",
    "campus",
    "library",
    "syllabus",
    "scholarship",
    "internship",
    "training",
    "coaching",
    "tuition",
    "result",
    "poor teaching",
    "harassment",
    "discrimination",
    "ragging",
    "facilities",
    "infrastructure",
    "attendance",
    "discipline",
    "placement",
    "hostel",
    "canteen",
    "staff behavior",
    "examination",
    "marks",
    "evaluation",
    "semester",
    "practical",
    "laboratory",
    "workshop",
    "grievance",
    "administration",
    "department",
    "dean",
    "principal",
  ],
  banking: [
    "bank",
    "credit",
    "debit",
    "card",
    "account",
    "transaction",
    "atm",
    "deposit",
    "withdrawal",
    "transfer",
    "loan",
    "mortgage",
    "interest",
    "payment",
    "balance",
    "overdraft",
    "statement",
    "upi",
    "netbanking",
    "cheque",
    "fund",
    "wire transfer",
    "neft",
    "rtgs",
    "swift",
    "forex",
    "fraud",
    "scam",
    "unauthorized",
    "declined",
    "blocked",
    "frozen",
    "wrong debit",
    "failed transaction",
    "technical issue",
    "server down",
    "poor service",
    "queue",
    "waiting time",
    "hidden charges",
    "penalty",
    "processing fee",
    "late fee",
    "dispute",
    "kyc",
    "password reset",
    "pin",
    "branch",
    "manager",
    "money stolen",
    "account hacked",
    "banking nightmare",
    "financial disaster",
    "bank fraud",
    "money lost",
    "banking hell",
    "account frozen",
    "banking horror",
    "financial mess",
    "money missing",
    "unauthorized transaction",
    "banking scam",
    "financial fraud",
    "bank error",
    "account blocked",
    "banking disaster",
    "financial nightmare",
    "bank mistake",
    "money gone",
    "banking chaos",
    "financial horror",
    "bank blunder",
    "money trapped",
    "banking catastrophe",
    "fraudulent charges",
    "unauthorized access",
    "account compromise",
    "identity theft",
    "banking fraud",
    "financial loss",
    "money problems",
    "banking issues",
    "account problems",
    "transaction failure",
    "payment declined",
    "card declined",
    "payment failed",
    "transaction error",
    "payment issue",
    "mobile banking",
    "internet banking",
    "digital banking",
    "online banking",
    "banking services",
    "bank account",
    "savings account",
    "current account",
    "fixed deposit",
    "recurring deposit",
    "bank statement",
    "passbook",
    "bank branch",
    "bank manager",
    "bank employee",
    "banking hours",
    "minimum balance",
    "account balance",
    "bank charges",
    "service charges",
  ],
  finance: [
    "investment",
    "stock",
    "mutual fund",
    "insurance",
    "premium",
    "claim",
    "policy",
    "trading",
    "dividend",
    "portfolio",
    "broker",
    "market",
    "shares",
    "bonds",
    "wealth",
    "financial",
    "advisory",
    "tax saving",
    "credit score",
    "loan approval",
    "bankruptcy",
    "hedge fund",
    "inflation",
    "fraud",
    "mismanagement",
    "default",
    "penalty",
    "hidden charges",
    "misleading",
    "poor returns",
    "delayed payment",
    "wrong calculation",
    "processing delay",
    "rejection",
    "risk",
    "volatility",
    "market crash",
    "documentation",
    "verification",
    "audit",
    "compliance",
    "tax filing",
    "penalty",
  ],
  travel: [
    "flight",
    "hotel",
    "booking",
    "reservation",
    "cancellation",
    "refund",
    "ticket",
    "accommodation",
    "travel",
    "holiday",
    "package",
    "tour",
    "visa",
    "passport",
    "itinerary",
    "airline",
    "baggage",
    "cruise",
    "excursion",
    "tourist spot",
    "guide",
    "sightseeing",
    "staycation",
    "delay",
    "cancellation",
    "overbooking",
    "poor service",
    "dirty room",
    "bad condition",
    "mismanagement",
    "lost booking",
    "wrong dates",
    "hidden charges",
    "amenities",
    "food quality",
    "cleanliness",
    "security",
    "staff behavior",
    "check-in",
    "check-out",
    "layover",
    "connection",
    "immigration",
    "customs",
    "staff",
    "behavior",
    "check-in",
    "check-out",
    "layover",
  ],
  insurance: [
    "policy",
    "claim",
    "premium",
    "coverage",
    "accident",
    "health insurance",
    "life insurance",
    "vehicle insurance",
    "renewal",
    "settlement",
    "nominee",
    "term plan",
    "maturity",
    "benefits",
    "compensation",
    "deductible",
    "policyholder",
    "endorsement",
    "liability",
    "underwriting",
    "rejection",
    "delay",
    "partial payment",
    "wrong calculation",
    "mis-selling",
    "fraud",
    "agent behavior",
    "documentation",
    "processing time",
    "verification",
    "investigation",
    "surveyor",
    "paperwork",
    "policy terms",
    "exclusions",
    "conditions",
    "pre-existing",
    "waiting period",
    "network hospital",
    "cashless",
  ],
  government: [
    "passport",
    "visa",
    "license",
    "certificate",
    "registration",
    "tax",
    "document",
    "application",
    "scheme",
    "pension",
    "identity",
    "aadhar",
    "pan card",
    "voter id",
    "government office",
    "public service",
    "subsidy",
    "ration card",
    "municipal",
    "court",
    "legislation",
    "GST",
    "delay",
    "corruption",
    "bribe",
    "poor service",
    "harassment",
    "wrong information",
    "lost documents",
    "verification",
    "rejection",
    "queue",
    "waiting time",
    "official",
    "department",
    "ministry",
    "bureaucracy",
    "red tape",
    "procedure",
    "deadline",
    "fine",
    "penalty",
    "compliance",
    "authority",
    "railway",
    "railway reservation",
    "railway ticket",
    "railway booking",
    "railway cancellation",
    "railway refund",
    "railway delay",
    "transport",
    "police",
    "law",
  ],
  entertainment: [
    "movie",
    "show",
    "movie ticket",
    "booking",
    "streaming",
    "subscription",
    "channel",
    "content",
    "platform",
    "event",
    "concert",
    "performance",
    "theatre",
    "entertainment",
    "music",
    "live",
    "broadcast",
    "gaming",
    "sports",
    "festival",
    "recreation",
    "comedy",
    "drama",
    "series",
    "poor quality",
    "buffering",
    "technical issue",
    "server down",
    "wrong show",
    "cancelled",
    "overbooked",
    "bad experience",
    "customer service",
    "billing issue",
    "account problem",
    "password reset",
    "subscription",
    "connection",
    "streaming quality",
    "advertisement",
    "content",
    "censorship",
    "inappropriate",
    "offensive",
    "vulgar",
    "obscene",
    "pornographic",
    "explicit",
    "inappropriate content",
    "subscription",
    "connection",
    "streaming quality",
    "offensive content",
    "vulgar content",
    "obscene content",
    "pornographic content",
    "explicit content",
  ],
  ecommerce: [
    "order",
    "delivery",
    "product",
    "refund",
    "return",
    "shipping",
    "package",
    "item",
    "purchase",
    "seller",
    "shop",
    "store",
    "online",
    "tracking",
    "payment",
    "price",
    "discount",
    "marketplace",
    "cart",
    "wishlist",
    "flash sale",
    "coupon",
    "customer service",
    "exchange",
    "damaged",
    "wrong item",
    "fake product",
    "delayed delivery",
    "missing item",
    "poor quality",
    "cancellation",
    "return issue",
    "refund delay",
    "payment failure",
    "checkout",
    "address",
    "delivery agent",
    "packaging",
    "warranty",
    "guarantee",
    "authenticity",
    "size issue",
    "color mismatch",
    "damaged",
    "defective",
    "broken",
    "faulty",
    "customer service",
    "billing issue",
    "account problem",
    "password reset",
  ],
  utility: [
    "electricity",
    "water",
    "gas",
    "bill",
    "connection",
    "meter",
    "supply",
    "power",
    "utility",
    "service",
    "maintenance",
    "repair",
    "installation",
    "consumption",
    "tariff",
    "payment",
    "outage",
    "network",
    "sewage",
    "waste disposal",
    "recharge",
    "billing cycle",
    "power cut",
    "voltage issue",
    "leakage",
    "low pressure",
    "contamination",
    "wrong reading",
    "excessive bill",
    "connection issue",
    "disconnection",
    "restoration",
    "technician",
    "breakdown",
    "emergency",
    "safety",
    "hazard",
    "damage",
    "infrastructure",
    "underground",
    "overhead",
  ],
  telecom: [
    "network",
    "signal",
    "call",
    "mobile",
    "phone",
    "sim",
    "data",
    "internet",
    "recharge",
    "prepaid",
    "postpaid",
    "roaming",
    "coverage",
    "4g",
    "5g",
    "3g",
    "broadband",
    "fiber",
    "wifi",
    "hotspot",
    "connection",
    "disconnection",
    "activation",
    "deactivation",
    "port",
    "number portability",
    "billing",
    "plan",
    "pack",
    "tariff",
    "unlimited",
    "validity",
    "expiry",
    "balance",
    "call drop",
    "poor signal",
    "network issue",
    "no network",
    "weak signal",
    "call quality",
    "voice clarity",
    "internet speed",
    "slow internet",
    "data speed",
    "buffering",
    "network congestion",
    "service disruption",
    "wrong billing",
    "excess charge",
    "unwanted service",
    "value added service",
    "spam call",
    "promotional call",
    "customer care",
    "network outage",
    "service outage",
    "poor connectivity",
    "network failure",
    "call failure",
    "data usage",
    "data limit",
    "fair usage policy",
    "network switching",
    "call barring",
    "caller tune",
    "mobile number",
    "phone number",
    "network bar",
    "sim block",
    "sim activation",
    "network registration",
    "call center",
    "helpline",
    "customer support",
    "service center",
    "network coverage",
    "dead zone",
    "signal strength",
    "tower",
    "telecom provider",
    "telecom service",
    "mobile service",
    "phone service",
    "cellular network",
    "mobile network",
    "network provider",
    "internet provider",
    "broadband provider",
    "fiber connection",
    "wireless connection",
    "data plan",
    "calling plan",
    "mobile plan",
    "network speed",
    "data speed",
    "download speed",
    "upload speed",
  ],
  utilities: [
    "electricity",
    "power",
    "water",
    "gas",
    "utility bill",
    "meter",
    "connection",
    "supply",
    "voltage",
    "current",
    "power cut",
    "blackout",
    "outage",
    "load shedding",
    "meter reading",
    "billing",
    "consumption",
    "pipeline",
    "water pressure",
    "gas leak",
    "power surge",
    "fluctuation",
    "electric shock",
    "transformer",
    "power line",
    "wire",
    "cable",
    "water supply",
    "water shortage",
    "water contamination",
    "water quality",
    "gas pressure",
    "gas connection",
    "gas cylinder",
    "pipeline damage",
    "meter tampering",
    "faulty meter",
    "wrong reading",
    "excessive bill",
    "billing error",
    "connection fee",
    "disconnection",
    "reconnection",
    "power failure",
    "emergency repair",
    "maintenance work",
    "scheduled outage",
    "unscheduled outage",
    "power theft",
    "illegal connection",
    "meter box",
    "fuse",
    "circuit breaker",
    "water tank",
    "water pump",
    "water meter",
    "gas meter",
    "electric meter",
    "power distribution",
    "water distribution",
    "gas distribution",
    "utility pole",
    "underground cable",
    "overhead line",
    "water pipe",
    "gas pipe",
    "sewage",
    "drainage",
    "waste water",
    "power station",
    "substation",
    "water treatment",
    "water plant",
    "power plant",
    "gas plant",
    "utility service",
    "utility provider",
  ],
  farming: [
    "agriculture",
    "crops",
    "farming",
    "farming equipment",
    "irrigation",
    "pesticides",
    "harvest",
    "soil health",
    "organic farming",
    "dairy farming",
    "fertilizers",
    "rural development",
    "agriculture loan",
    "agriculture insurance",
    "agriculture extension",
    "agriculture research",
    "agriculture development",
    "agriculture extension",
    "agriculture research",
  ],
  it: [
    "software",
    "hardware",
    "networking",
    "cloud computing",
    "cybersecurity",
    "programming",
    "AI",
    "machine learning",
    "data science",
    "app development",
    "tech support",
    "IT",
    "malware",
    "cybersecurity",
    "cyber attack",
    "cyber security",
    "cyber threat",
    "cyber crime",
    "cyber fraud",
    "cyber security breach",
    "cyber security attack",
    "cyber security threat",
    "cyber security crime",
    "cyber security fraud",
    "cyber security breach",
    "technology",
    "IT",
    "IT support",
    "IT service",
    "IT solution",
    "IT consultant",
    "IT consultant",
  ],
};

// Calculate similarity score between input text and category keywords
function calculateSimilarity(text: string, keywords: string[]): number {
  const words = text.toLowerCase().split(/\W+/);
  let matches = 0;

  for (const word of words) {
    if (keywords.includes(word)) {
      matches++;
    }
  }

  return matches / Math.sqrt(words.length * keywords.length);
}

// Get suggested categories based on input text
export const getSuggestedCategories = (
  text: string,
  categories: Category[]
) => {
  // Split input text into words and clean them
  const words = text
    .toLowerCase()
    .split(/\s+/)
    .map((word) => word.trim())
    .filter((word) => word.length > 0);

  // Create word pairs for matching multi-word keywords (e.g., "mutual fund")
  const wordPairs = words
    .slice(0, -1)
    .map((word, i) => `${word} ${words[i + 1]}`);
  const allPhrases = [...words, ...wordPairs];
  // Score each category based on exact keyword matches
  const scores = categories.map((category) => {
    const keywords =
      categoryKeywords[category.id as keyof typeof categoryKeywords] || [];
    const matchCount = allPhrases.reduce((count, phrase) => {
      return count + (keywords.includes(phrase) ? 1 : 0);
    }, 0);
    return { category, score: matchCount };
  });

  // Return only categories with exact matches, sorted by score
  return scores
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((item) => item.category);
};

// Get relevant companies based on category and text input
export function getRelevantCompanies(
  text: string,
  category: Category,
  threshold = 0.1
): typeof category.companies {

  return category.companies
    .map((company) => ({
      company,
      score: calculateSimilarity(text, [
        company.name.toLowerCase(),
        ...(categoryKeywords[category.id as keyof typeof categoryKeywords] ||
          []),
      ]),
    }))
    .filter((item) => item.score > threshold)
    .sort((a, b) => b.score - a.score)
    .map((item) => item.company);
}
